name: 'Nathan Douglas'
social:
  devto: ''
  discord: ''
  discord_invite: ''
  email: 'blog@darkdell.net'
  gitea: ''
  github: 'ndouglas'
  goodreads: '162844962-nathan-douglas'
  hack_the_box: ''
  hackernews: 'nathan_douglas'
  kaggle: ''
  lichess: ''
  linked_in: 'nathan-douglas-101826145/'
  matrix: ''
  pleroma: ''
  reddit: 'nathan_douglas'
  root_me: ''
