main:
- identifier: 'home'
  name: 'Home'
  pre: ''
  post: ''
  url: /
  weight: -3
- identifier: 'about'
  name: 'About Me'
  pre: ''
  post: ''
  url: /about/
  weight: -2
- identifier: 'projects'
  name: 'Projects'
  pre: ''
  post: ''
  url: /projects/
  weight: -1
- identifier: 'ideas'
  name: 'Ideas'
  pre: ''
  post: ''
  url: /ideas/
  weight: -1
