main:
- identifier: 'home'
  name: 'Home'
  pre: ''
  post: ''
  url: /
  weight: -3
- identifier: 'about'
  name: 'About Me'
  pre: ''
  post: ''
  url: /about/
  weight: -2
- identifier: 'posts'
  name: 'Posts'
  pre: ''
  post: ''
  url: /posts/
  weight: -1
