enableInlineShortcodes: false
exec:
  allow:
  - ^dart-sass-embedded$
  - ^go$
  - ^npx$
  - ^postcss$
  osEnv:
  - (?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+)$
funcs:
  getenv:
  - ^HUGO_
  - ^CI$
http:
  methods:
  - (?i)GET|POST
  urls:
  - .*