name: Continuous Integration
on:
  pull_request:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Post-Checkout Actions
        uses: ./.github/actions/post-checkout

      - name: Lint
        run: |
          cargo fmt -- --check;
          cargo clippy -- -D warnings;         

      - name: Test
        run: |
          cargo check;
          cargo test --all;
